name: Telegram Release Notification  
  
on:  
  create:  
    tags:  
      - '*' # 监听所有新的release标签  
  
jobs:  
  notify:  
    name: Send Telegram Message  
    runs-on: ubuntu-latest  
    steps:  
      - name: Send Telegram Message  
        uses: appleboy/telegram-action@master  
        env:  
          TELEGRAM_CHAT_ID: -1001917136075 # 替换为您的Telegram群组ID  
          TELEGRAM_BOT_TOKEN: 7088187094:AAFtSYKr8gMnt7e1kCRUHxGfvLOMvtYt0cg # 替换为您的Telegram Bot API token  
        with:  
          to: ${{ env.TELEGRAM_CHAT_ID }}  
          token: ${{ env.TELEGRAM_BOT_TOKEN }}  
          message: |  
            New Release Notification!  
            Repository: ${{ github.repository }}  
            Release Tag: ${{ github.ref }}  
            Created by: ${{ github.actor }}  
            基于Lede的OpenWrt更新: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref }}
